Add more documentation for WebKitGTK and WPE WebKit
WebKit/Documentation pull request #48
Opened 2023-05-11 18:05 UTC by mcatanzaro

This adds various WPE/GTK documentation rescued from trac.

(I'm ignoring the commit message template because I don't see any hook to use for generating it.)

2023-05-11 18:08 UTC, mcatanzaro commented
One more thing: if we want to create a redirect from the old location of the security page to the new location under Ports, we could use https://github.com/mkdocs/mkdocs-redirects

2023-05-11 18:37 UTC, stwrt submitted a review, later dismissed
Just some minor comments from a read through.

2023-05-11 18:37 UTC, stwrt commented on docs/Ports/WebKitGTK and WPE WebKit/Dependencies Policy.md
> +| Debian 10 (Buster)             | 2019-07-06   | 2022-08-14         |
When should we delete unsupported versions from this table?

2023-05-11 18:37 UTC, stwrt commented on docs/Ports/WebKitGTK and WPE WebKit/Security_Updates.md
> +Before reading this document, please also [learn about WebKit ports](../Introduction.md) and [WebKitGTK and WPE WebKit releases and versioning](Releases and Versioning.md).
I would prefer not to use full paths like `/Ports/Introduction.md` instead. This makes it easier to update if we need to move a file around.

2023-05-11 19:34 UTC, fujii commented
@stwrt : BuildOptions.md is using camel case, "Dependencies Policy.md" is using a white space, Security_Updates.md is using a underscore. Do we have a policy for filenames?

2023-05-11 19:36 UTC, clopez requested changes

2023-05-11 19:36 UTC, clopez commented on docs/Ports/WebKitGTK and WPE WebKit/Security_Updates.md
> +* The major version rarely changes, but if it does then you may need to check if the application code still builds and works fine with the new major version. In that case there should be a guide expl
I think some of this doc is duplicated with [Security/GTK_WPE_Security_Updates.md](https://github.com/WebKit/Documentation/blob/main/docs/Security/GTK_WPE_Security_Updates.md)

That document `Security/GTK_WPE_Security_Updates.md` was created using the info that trac that you are moving here now. So instead of adding here duplicated info just link to the document already in this repo which is a version newer than what was on trac.

2023-05-11 19:51 UTC, fujii commented
@stwrt : Another style question I'm wondering is about single line breaks. Which style do we prefer? 
This is a controversial topic at Wikipedia. https://en.wikipedia.org/wiki/Wikipedia:Line_breaks_usage

2023-05-11 19:51 UTC, mcatanzaro commented on docs/Ports/WebKitGTK and WPE WebKit/Dependencies Policy.md
> +| Debian 10 (Buster)             | 2019-07-06   | 2022-08-14         |
I don't really care. I almost removed it. Can do you here if you prefer.

2023-05-11 19:52 UTC, mcatanzaro commented on docs/Ports/WebKitGTK and WPE WebKit/Security_Updates.md
> +* The major version rarely changes, but if it does then you may need to check if the application code still builds and works fine with the new major version. In that case there should be a guide expl
This PR actually deletes the original file (which is why I CCed you here).

2023-05-11 19:55 UTC, mcatanzaro commented on docs/Ports/WebKitGTK and WPE WebKit/Security_Updates.md
> +Before reading this document, please also [learn about WebKit ports](../Introduction.md) and [WebKitGTK and WPE WebKit releases and versioning](Releases and Versioning.md).
I think you meant "I would prefer to use full paths" right? I can if you want, but [mkdocs discourages this](https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links) and says it's not supported, even though it clearly does work.

2023-05-11 19:58 UTC, mcatanzaro commented
> BuildOptions.md is using camel case, "Dependencies Policy.md" is using a white space, Security_Updates.md is using a underscore. Do we have a policy for filenames?

Hm, indeed, it seems most existing markdown files use camel case. I'll switch these to camel case for consistency with what we already have.

(The directory names necessarily have to use white space because they affect the generated output.)

2023-05-11 19:59 UTC, mcatanzaro commented
> Another style question I'm wondering is about single line breaks. Which style do we prefer?
This is a controversial topic at Wikipedia. https://en.wikipedia.org/wiki/Wikipedia:Line_breaks_usage

I never imagined there could exist proponents of single line breaks. :D

2023-05-11 20:12 UTC, stwrt commented
> @stwrt : BuildOptions.md is using camel case, "Dependencies Policy.md" is using a white space, Security_Updates.md is using a underscore. Do we have a policy for filenames?

Good point. We don't have a policy yet, but camel case would work well.

I'll actually need to go back and update a lot of the file names too, because I was not super consistent when getting this started.

2023-05-11 20:50 UTC, clopez commented on docs/Ports/WebKitGTK and WPE WebKit/Security_Updates.md
> +* The major version rarely changes, but if it does then you may need to check if the application code still builds and works fine with the new major version. In that case there should be a guide expl
oook... I need a coffee :)

2023-05-11 21:02 UTC, clopez requested changes

2023-05-11 21:02 UTC, clopez commented on docs/Ports/Introduction.md
> +
I would add here more information that is useful for newcomers that have no idea of what a port is and about releases or security updates.

Suggested text to use:


```
# What Are WebKit Ports?


WebKit has been "ported" to various platforms and operating systems.
The platform-specific bits of each one of this "ports" is maintained by
different teams that collaborate between them on the platform-agnostic bits.

The code for upstream ports is maintained directly in the [WebKit GitHub repository](https://github.com/WebKit/webkit). 
But the WebKit project itself doesn't do releases or security advisories.

The task of doing the releases and/or the security advisories is the responsibility of each one of the ports.
Please refer to the documentation of each port to find out more about their release process.

Below there is a list of ports that are available on the upstream repository:

```

2023-05-11 21:16 UTC, clopez commented
> > @stwrt : BuildOptions.md is using camel case, "Dependencies Policy.md" is using a white space, Security_Updates.md is using a underscore. Do we have a policy for filenames?
> 
> Good point. We don't have a policy yet, but camel case would work well.
> 
> I'll actually need to go back and update a lot of the file names too, because I was not super consistent when getting this started.

+1 for CamelCase

Dealing with spaces on filenames is a bit annoying when using the shell

2023-05-16 18:48 UTC, mcatanzaro commented on docs/Ports/WebKitGTK and WPE WebKit/Security_Updates.md
> +Before reading this document, please also [learn about WebKit ports](../Introduction.md) and [WebKitGTK and WPE WebKit releases and versioning](Releases and Versioning.md).
I'll plan to stick with relative paths unless you tell me otherwise.

2023-05-16 18:49 UTC, mcatanzaro commented on docs/Ports/WebKitGTK and WPE WebKit/Dependencies Policy.md
> +| Debian 10 (Buster)             | 2019-07-06   | 2022-08-14         |
Seems harmless to keep it.

2023-05-16 18:52 UTC, mcatanzaro commented on docs/Ports/Introduction.md
> +
I've adjusted the first part of the text to include some of this.

I think the discussion of releases and security advisories is already adequately addressed at the bottom of this file.

2023-05-16 18:54 UTC, mcatanzaro commented
Updated.

2023-05-16 21:32 UTC, mcatanzaro commented
OK, @stwrt says on Slack that this pull request looks OK to him. @clopez if you're happy too, then please approve it (or request changes). Thanks.

2023-05-16 21:43 UTC, stwrt reviewed
Can you just squash these commits, and I think we can land.

2023-05-17 14:39 UTC, mcatanzaro commented
I had not intended for these to be squashed, but whatever. Will squash and then land.

2023-05-17 15:29 UTC, merged