Removed "Ports/Windows port" subdirectory which contained a single file
WebKit/Documentation pull request #56
Opened 2023-06-29 04:52 UTC by fujii

* Renamed "Ports/Windows port/Introduction.md" to "Ports/WindowsPort.md"
* Fixed broken links.

2023-06-29 08:12 UTC, stwrt requested changes
Two very minor things. The .html seems to be breaking the links when testing this locally. Does it work for you?

2023-06-29 08:12 UTC, stwrt commented on docs/Build & Debug/BuildOptions.md
> -For building WebKit on Windows, see [Windows Port](../Ports/Windows port/Introduction.html).
Adding .html causes the link to fail. Removing .html seems to fix the link.

2023-06-29 08:12 UTC, stwrt commented on docs/Ports/WindowsPort.md
> -You can run programs under a debugger with [this instruction](../../Build & Debug/DebuggingWithVS.html).
Adding .html causes the link to fail. Removing .html seems to fix the link.

2023-06-29 10:04 UTC, fujii commented on docs/Build & Debug/BuildOptions.md
> -For building WebKit on Windows, see [Windows Port](../Ports/Windows port/Introduction.html).
It works fine with `.html`, but doesn't work without `.html` on my PC.
The following line also appends `.html`. 
https://github.com/WebKit/Documentation/blob/main/docs/Getting%20Started/ContributingCode.md?plain=1#L15
The link on the web site is broken.
https://docs.webkit.org/Getting%20Started/ContributingCode.html
MkDocs version issue?

2023-06-29 10:09 UTC, fujii commented on docs/Build & Debug/BuildOptions.md
> -For building WebKit on Windows, see [Windows Port](../Ports/Windows port/Introduction.html).
The document says we have to use relative paths and `.md` suffix.
https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages

2023-06-29 10:13 UTC, fujii commented on docs/Build & Debug/BuildOptions.md
> -For building WebKit on Windows, see [Windows Port](../Ports/Windows port/Introduction.html).
Fixed.

2023-06-29 10:13 UTC, fujii commented on docs/Ports/WindowsPort.md
> -You can run programs under a debugger with [this instruction](../../Build & Debug/DebuggingWithVS.html).
Fixed.

2023-08-27 18:15 UTC, stwrt approved these changes
Tested this again after upgrading mkdocs and it worked great. Must have been an issue on my end. Approving.

2023-08-27 18:16 UTC, stwrt commented
Looks like there were some merge conflicts that need to be resolved.

2023-08-27 19:58 UTC, merged