add more information for winget (eg. path settings)
WebKit/Documentation pull request #91
Opened 2024-04-17 07:56 UTC by r-otaka

add information of GnuWin32.Gperf
add reg add command for winget

2024-04-17 20:25 UTC, fujii requested changes

2024-04-17 20:25 UTC, fujii commented on docs/Ports/WindowsPort.md
> +https://gnuwin32.sourceforge.net/packages/gperf.htm
Because I have no problem with installing `GnuWin32.Gperf`, it's unclear to me when we can remove this sentence.
And, I think it isn't helpful information installing manually if winget fails.

If you want to add a link to gperf, how about an idea of adding a link to line#12.
https://github.com/WebKit/Documentation/blob/3c0f681af2dee4ea0355d17d9ce8b517d048538c/docs/Ports/WindowsPort.md?plain=1#L12

2024-04-17 20:25 UTC, fujii commented on docs/Ports/WindowsPort.md
> +An example using **Winget**
Use `WinGet` or `winget` rather than `Winget`.

https://github.com/microsoft/winget-cli
https://learn.microsoft.com/en-us/windows/package-manager/winget/

2024-04-18 00:41 UTC, r-otaka commented
Okay, I will modify.

2024-04-25 23:38 UTC, khei4 commented
#94 includes this change.

2024-05-16 23:46 UTC, closed without merging