Fix Windows port doc
WebKit/Documentation pull request #94
Opened 2024-04-25 23:37 UTC by khei4

- Add explanations on Using WinGet section
- Note [non-english system locale error ](https://bugs.webkit.org/show_bug.cgi?id=273060)on tests, 
- Fix typo

2024-04-25 23:51 UTC, fujii requested changes

2024-04-25 23:51 UTC, fujii commented on docs/Ports/WindowsPort.md
> +And double-click it to open PowerShell, we call this opend shell as "WebKit command prompt" hereafter.
opend → opened

2024-04-25 23:51 UTC, fujii commented on docs/Ports/WindowsPort.md
> +If you failed to install programs (excluding Python), please use `winget install --id (the name of failed to install programs. (eg, LLVM.LLVM))` command.
I don't think this sentence is needed.

2024-04-26 00:57 UTC, khei4 commented on docs/Ports/WindowsPort.md
> +And double-click it to open PowerShell, we call this opend shell as "WebKit command prompt" hereafter.
Oh, thank you for a good catch!

2024-04-26 01:04 UTC, fujii approved these changes

2024-04-26 01:06 UTC, merged